version: '3.8'

services:
  whatsapp-mod-bot:
    image: ghcr.io/thetechnikfreak/whatsappbot:latest
    container_name: whatsapp-mod-bot
    restart: unless-stopped
    volumes:
      # Persist WhatsApp session data
      - .wwebjs_auth:/app/.wwebjs_auth
      # Persist Bot configuration and stats
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - GROQ_API_KEY=
      - SUPERADMIN_NUMBER=

      
volumes:
  .wwebjs_auth:
